[package]
name = "heteroprof"
version = "0.1.0"
authors = ["Carl Pearson <carl.w.pearson@gmail.com>"]

[dependencies]
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
petgraph = "0.4.11"
cuckoofilter = "0.3"
gcollections = "0.3.5"
intervallum = "0.6.5"
